name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Show tree (debug)
        run: |
          pwd
          ls -la
          echo "---- firebase.json ----"
          cat firebase.json || true

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: riley-bmw-22879
          channelId: live
          entryPoint: .   # if firebase.json is in a subfolder, replace '.' with that folder name
